import { ChecklistDocumentItem } from '@/types/docente-checklist';

export const INITIAL_DOCENTE_CHECKLIST: ChecklistDocumentItem[] = [
  {
    id: 1,
    title: 'Certificado de cuenta bancaria actualizado y activado',
    shortDescription: 'Cuenta de ahorros o corriente a nombre del docente',
    instructions:
      'Expedición no mayor a treinta (30) días calendario. La certificación debe indicar que la cuenta se encuentra ACTIVA y especificar tipo de cuenta y número legible.',
    status: 'aprobado',
    fileName: 'certificacion_bancaria_bancolombia_activa.pdf',
    fileSize: 420000,
    uploadedAt: '2026-03-10T09:15:00Z',
    category: 'financiero',
  },
  {
    id: 2,
    title:
      'Oficio donde manifiesta libremente bajo gravedad de juramento que no devenga salario del Estado y que no está incurso en inhabilidad para cargos públicos',
    shortDescription: 'Manifestación juramentada de no doble asignación salarial',
    instructions:
      'Documento debidamente fechado y firmado en original o con firma digital válida. Debe incluir número de cédula y lugar de expedición.',
    status: 'aprobado',
    fileName: 'oficio_no_doble_asignacion_juramento.pdf',
    fileSize: 310000,
    uploadedAt: '2026-03-10T09:30:00Z',
    category: 'legal',
  },
  {
    id: 3,
    title: 'Formato de declaración juramentada',
    shortDescription: 'Formato institucional de la Secretaría de Educación',
    instructions:
      'Diligenciar todos los campos sin tachones ni enmendaduras. Asegurarse de consignar la información completa del cónyuge y familiares en primer grado si aplica.',
    status: 'aprobado',
    fileName: 'declaracion_juramentada_diligenciada.pdf',
    fileSize: 520000,
    uploadedAt: '2026-03-11T11:00:00Z',
    category: 'legal',
  },
  {
    id: 4,
    title: 'Formulario de afiliación a CAJAMAG (última versión, diligenciado y firmado)',
    shortDescription: 'Caja de Compensación Familiar del Magdalena',
    instructions:
      'Descargue la última versión directamente desde el portal oficial de CAJAMAG (cajamag.com.co). Diligencie datos del trabajador y personas a cargo con sus respectivos anexos.',
    specialNote: '⚠️ Verificar que corresponda a la versión vigente en la página web de CAJAMAG.',
    status: 'rechazado',
    fileName: 'formulario_cajamag_v2025.pdf',
    fileSize: 840000,
    uploadedAt: '2026-03-12T14:20:00Z',
    validatorComment:
      'El formulario adjunto corresponde a la versión 2024. Por favor descargar y diligenciar la versión 2026 actualizada disponible en la plataforma oficial de CAJAMAG, incluyendo la firma del solicitante.',
    category: 'seguridad_social',
  },
  {
    id: 5,
    title: 'Formato de Fiduprevisora, diligenciado y firmado',
    shortDescription: 'Afiliación al Fondo Nacional de Prestaciones Sociales del Magisterio (FOMAG)',
    instructions:
      'Diligenciar completamente el formulario de registro y vinculación médica de la Fiduprevisora para docentes oficiales del departamento del Magdalena.',
    status: 'en_revision',
    fileName: 'formato_fomag_fiduprevisora_firmado.pdf',
    fileSize: 670000,
    uploadedAt: '2026-03-14T10:10:00Z',
    category: 'seguridad_social',
  },
  {
    id: 6,
    title: 'Formato de bienes y rentas de la función pública, diligenciado y firmado',
    shortDescription: 'Declaración juramentada en plataforma SIGEP II',
    instructions:
      'Generar la declaración de bienes y rentas desde el portal SIGEP II con corte al año fiscal inmediatamente anterior. Debe contener código de barras o verificación digital del DAFP.',
    status: 'aprobado',
    fileName: 'declaracion_bienes_rentas_sigep2.pdf',
    fileSize: 450000,
    uploadedAt: '2026-03-11T15:40:00Z',
    category: 'legal',
  },
  {
    id: 7,
    title:
      'Certificado de delitos contra la libertad, integridad y formación sexuales (actualizado)',
    shortDescription: 'Certificado oficial expedido por la Policía Nacional (Ley 1918 de 2018)',
    instructions:
      'Requisito obligatorio para todo personal con contacto con menores de edad. Fecha de expedición no mayor a 15 días.',
    status: 'aprobado',
    fileName: 'certificado_ley1918_delitos_sexuales.pdf',
    fileSize: 290000,
    uploadedAt: '2026-03-12T08:00:00Z',
    category: 'antecedentes',
  },
  {
    id: 8,
    title: 'Antecedentes Procuraduría (actualizado)',
    shortDescription: 'Certificado ordinario o especial de antecedentes disciplinarios',
    instructions:
      'Descargado desde www.procuraduria.gov.co. Vigencia máxima de treinta (30) días a la fecha de radicación.',
    status: 'aprobado',
    fileName: 'antecedentes_procuraduria_marzo2026.pdf',
    fileSize: 210000,
    uploadedAt: '2026-03-12T08:10:00Z',
    category: 'antecedentes',
  },
  {
    id: 9,
    title: 'Antecedentes Contraloría (actualizado)',
    shortDescription: 'Boletín de responsables fiscales de la CGR',
    instructions:
      'Descargado desde www.contraloria.gov.co. Certifica la ausencia de deudas o responsabilidades fiscales pendientes con el Estado.',
    status: 'aprobado',
    fileName: 'antecedentes_fiscales_contraloria.pdf',
    fileSize: 195000,
    uploadedAt: '2026-03-12T08:15:00Z',
    category: 'antecedentes',
  },
  {
    id: 10,
    title: 'Antecedentes de medidas correctivas RNMC Policía (actualizado)',
    shortDescription: 'Registro Nacional de Medidas Correctivas (Código de Policía)',
    instructions:
      'Expedido por la Policía Nacional. Debe certificar que no registra medidas correctivas pendientes por infracciones al Código Nacional de Policía y Convivencia.',
    status: 'aprobado',
    fileName: 'medidas_correctivas_policia_rnmc.pdf',
    fileSize: 220000,
    uploadedAt: '2026-03-12T08:20:00Z',
    category: 'antecedentes',
  },
  {
    id: 11,
    title: 'Antecedentes Policía (actualizado)',
    shortDescription: 'Certificado de antecedentes judiciales en línea',
    instructions:
      'Consulta en línea de antecedentes judiciales de la Policía Nacional con fecha de consulta no superior a 15 días.',
    status: 'aprobado',
    fileName: 'antecedentes_judiciales_policia_nacional.pdf',
    fileSize: 230000,
    uploadedAt: '2026-03-12T08:25:00Z',
    category: 'antecedentes',
  },
  {
    id: 12,
    title: 'Experiencia laboral (certificados con cargo, fecha de ingreso y fecha de retiro)',
    shortDescription: 'Certificaciones laborales de instituciones educativas públicas o privadas',
    instructions:
      'Cada certificación debe contener membrete, NIT, teléfono de contacto verificable, funciones desempeñadas, fecha exacta de inicio (DD/MM/AAAA) y retiro.',
    specialNote: 'Deben anexarse ordenados cronológicamente desde el más reciente al más antiguo en un solo PDF.',
    status: 'en_revision',
    fileName: 'certificados_experiencia_laboral_docente.pdf',
    fileSize: 1850000,
    uploadedAt: '2026-03-13T16:00:00Z',
    category: 'academico',
  },
  {
    id: 13,
    title:
      'Copia autenticada de diplomas y actas de grado (bachiller, normalista, licenciado, especialista, etc.) y tarjeta profesional',
    shortDescription: 'Títulos académicos y tarjeta profesional o escalafón',
    instructions:
      'Escaneo a color de los diplomas con sus correspondientes actas de grado legibles. En caso de contar con tarjeta profesional o resolución de escalafón nacional docente, adjuntarla.',
    specialNote: 'Asegúrese de que el folio y número de libro de las actas de grado sean 100% legibles.',
    status: 'aprobado',
    fileName: 'titulos_actas_grado_licenciatura_matematicas.pdf',
    fileSize: 3200000,
    uploadedAt: '2026-03-11T16:30:00Z',
    category: 'academico',
  },
  {
    id: 14,
    title: 'Formato único de hoja de vida de la función pública, diligenciado y firmado',
    shortDescription: 'Formato DAFP para persona natural',
    instructions:
      'Diligenciado completamente en computador sin dejar campos obligatorios en blanco. Debe incluir la firma del docente en la última página.',
    status: 'aprobado',
    fileName: 'hoja_vida_funcion_publica_firmada.pdf',
    fileSize: 580000,
    uploadedAt: '2026-03-11T14:10:00Z',
    category: 'legal',
  },
  {
    id: 15,
    title:
      'Acreditar definición de situación militar (varones menores de 50 años) — libreta militar o soporte de trámite',
    shortDescription: 'Libreta militar de primera o segunda clase, o constancia de liquidación',
    instructions:
      'Aplica para varones menores de 50 años de edad. En caso de estar en trámite, adjuntar certificado oficial expedido por el Distrito Militar correspondiente.',
    specialNote: 'ℹ️ Exclusivo para varones menores de 50 años. Si usted es mujer o mayor de 50 años, adjunte constancia o documento aclaratorio.',
    status: 'aprobado',
    fileName: 'libreta_militar_primera_clase.pdf',
    fileSize: 490000,
    uploadedAt: '2026-03-10T10:00:00Z',
    category: 'legal',
  },
  {
    id: 16,
    title: 'Registro civil legible',
    shortDescription: 'Copia del registro civil de nacimiento',
    instructions:
      'Copia nítida del registro civil expedido por Notaría o Registraduría Nacional del Estado Civil con sello legible.',
    status: 'aprobado',
    fileName: 'registro_civil_nacimiento_notaria.pdf',
    fileSize: 720000,
    uploadedAt: '2026-03-10T10:20:00Z',
    category: 'legal',
  },
  {
    id: 17,
    title: 'Fotocopia de la cédula al 150%',
    shortDescription: 'Documento de identidad ampliado por ambas caras',
    instructions:
      'Fotocopia ampliada al 150% de la Cédula de Ciudadanía vigente (amarilla con hologramas o digital), ambas caras visibles en una sola página, nítida y legible.',
    specialNote: '⚠️ La ampliación debe ser exactamente al 150% y los números deben ser completamente legibles.',
    status: 'rechazado',
    fileName: 'cedula_100_tamano_real.pdf',
    fileSize: 340000,
    uploadedAt: '2026-03-12T16:45:00Z',
    validatorComment:
      'La fotocopia fue escaneada en tamaño real (100%) y la huella dactilar se encuentra borrosa. Se requiere que la cédula esté ampliada al 150% en ambas caras con total nitidez.',
    category: 'legal',
  },
  {
    id: 18,
    title: 'Oficio de aceptación del nombramiento',
    shortDescription: 'Carta formal dirigida a la Secretaría de Educación del Magdalena',
    instructions:
      'Documento escrito donde el docente manifiesta expresamente la aceptación del cargo y la plaza asignada, indicando el número de acto administrativo correspondiente.',
    status: 'en_revision',
    fileName: 'oficio_aceptacion_plaza_magdalena.pdf',
    fileSize: 390000,
    uploadedAt: '2026-03-14T11:25:00Z',
    category: 'nombramiento',
  },
  {
    id: 19,
    title: 'Notificación o comunicación del acto de nombramiento',
    shortDescription: 'Comunicación oficial enviada por la Secretaría',
    instructions:
      'Copia de la constancia de notificación personal o por correo electrónico del decreto o resolución de nombramiento en periodo de prueba o propiedad.',
    status: 'aprobado',
    fileName: 'comunicacion_notificacion_nombramiento.pdf',
    fileSize: 460000,
    uploadedAt: '2026-03-10T11:30:00Z',
    category: 'nombramiento',
  },
  {
    id: 20,
    title: 'Acto administrativo de nombramiento',
    shortDescription: 'Decreto departamental de la Gobernación del Magdalena',
    instructions:
      'Copia íntegra del Decreto Departamental emitido por la Gobernación del Magdalena que formaliza el nombramiento en el cargo docente.',
    status: 'aprobado',
    fileName: 'decreto_departamental_nombramiento_docente.pdf',
    fileSize: 950000,
    uploadedAt: '2026-03-10T11:45:00Z',
    category: 'nombramiento',
  },
  {
    id: 21,
    title: 'Comprobante de pago de estampilla (Gestión Tributaria)',
    shortDescription: 'Recibo oficial de pago de la estampilla departamental Pro-Desarrollo',
    instructions:
      'Comprobante de liquidación y pago bancario emitido por la Dirección de Gestión Tributaria del Departamento del Magdalena para actos de nombramiento.',
    specialNote: 'Verifique que figure el timbre del banco y el código de barras de la transacción tributaria.',
    status: 'pendiente',
    category: 'financiero',
  },
  {
    id: 22,
    title: 'Examen médico ocupacional de ingreso (IPS autorizada)',
    shortDescription: 'Certificado de aptitud médica laboral para docencia',
    instructions:
      'Certificado de aptitud psicofísica y laboral expedido por una Institución Prestadora de Salud (IPS) autorizada y con licencia en Salud Ocupacional vigente.',
    specialNote: 'El examen debe tener una vigencia no mayor a 30 días calendario y declarar al docente APTO.',
    status: 'pendiente',
    category: 'seguridad_social',
  },
  {
    id: 23,
    title: 'Acta de posesión',
    shortDescription: 'Documento final suscrito ante la autoridad nominadora o delegado',
    instructions:
      'Acta formal de posesión en el cargo docente. Se suscribe una vez aprobados los ítems anteriores ante la Secretaría de Educación o el Rector delegado.',
    specialNote: '📌 Este documento culmina el proceso oficial de vinculación.',
    status: 'pendiente',
    category: 'nombramiento',
  },
];
